oneweb_elasticsearch_image:
    build: elasticsearch/
    user: oneweb

oneweb_logstash_image:
    build: logstash/
    user: oneweb
    links:
      - oneweb_elasticsearch_image

oneweb_kibana_image:
    build: kibana/
    user: oneweb
    volumes:
      - /root/docker-ELK/data:/opt/oneweb/data
    ports:
      - "5601:5601"
    links:
      - oneweb_elasticsearch_image

oneweb_filebeat_image:
    build: filebeat/
    user: oneweb
    links:
      - oneweb_logstash_image

oneweb_sdk_image_1:
    build: oneweb/
    
    volumes:
      - /root/docker-ELK/nginx-log-1:/var/log/nginx
    ports:
      - "8080:80"
    links:
      - oneweb_logstash_image

oneweb_sdk_image_2:
    build: oneweb/
    volumes:
      - /root/docker-ELK/nginx-log-2:/var/log/nginx
    ports:
      - "8081:80"
    links:
      - oneweb_logstash_image