oneweb_elasticsearch_image:
    build: elasticsearch/
    container_name: oneweb_elasticsearch_container
    user: oneweb

oneweb_logstash_image:
    build: logstash/
    container_name: oneweb_logstash_container
    user: oneweb
    links:
      - oneweb_elasticsearch_container
